### ISSUE TITLE
ToDo list for new version

### ISSUE THREAD

**Issue by dani007200964** [dani007200964/Shellminator#14]
- [x] progress bar
- [x] remove error logs from getCursorPosition
- [x] select prompt with arrows
- [x] Non blocking plotter and prompts, maybe separate graphical unit?
- [x] static functions for formatting and terminal control:
    - [x] input prompt
    - [x] clear
- [x] PC simulator
- [x] Colorizer for command argument highlighting.
- [x] Terminal frontend detection and auto settings( Ctrl+E or ASCII 5 query )
- [x] Password protection
- [x] Doxygen theme as submodule
- [x] Plotter :construction:
- [x] Mouse Interface :construction:
- [x] Separated source files :construction:
- [ ] Unit tests :construction: 
- [x] Buffered printer
- [ ] Enable almost all functions on any platform :construction:
- [x] Better configuration header :construction:
- [x] Better documentation: :construction:
    - [x] More examples :construction:
    - [ ] Coverage report :construction:
    - [x] Interactive demo for each example :construction:

:construction: - means under development
