### ISSUE TITLE
TODO list for V1.2.0

### ISSUE THREAD

**Issue by dani007200964** [dani007200964/Shellminator#7]
# Todo list for the next release!

- [x] Override callback functions for the new shortcut keys
- [x] Option to set the timeout of the internal client
- [x] Advanced search functions
- [x] Banner text change option.
- [x] Path text change option. Also change it to blue color
- [x] Websocket channel
- [x] xTerm.js example
- [x] Terminal buzzer command, with mute option
- [x] QR-code generation with stronger devices
- [ ] Enum for key parser state machine. It's getting uglier every day.
- [ ] Documenting the shortcut keys
- [ ] Documenting the new functions
- [x] Tests with other platforms( STM32... )
- [ ] Check Commander compatibility
- [x] Move configuration to Shellminator-Settings.hpp
- [x] OPTIONAL: Better logo and footer.
- [x] Clear screen combo for CTRL-L key
- [x] History command
- [x] Help command
- [x] Page Down bug.
- [x] Modify it to use Stream class
- [ ] Update examples with Stream
- [ ] Modify GitHub Actions for new examples
- [ ] Password protection
- [ ] Progress bar

# Examples for the new stuff

- [x] Websocket single
- [x] Websocket multiple
- [ ] QR-Code

# Bugs with tests

- [x] Client flush required for ESP8266 ( Also it can be good on ESP32 ) at client disconnection
- [x] ESP8266 HTML responses are require PROGMEM option
- [x] ESP8266 handles client.connected differently() -> client.status() == ESTABLISHED has to be used
- [ ] ESP8266 websocket close event appears as "died" in browser.

**Comment by dani007200964** [comment]
Page-Up and Page-Down search function prototype added in badc44d995859c7b050912d2cbe9299a4f19e4bb

**Comment by dani007200964** [comment]
Crude prototype added for the reverse-i-search function.

https://user-images.githubusercontent.com/26076131/190501257-2e3c3b09-2503-4e33-ae7c-66663c4ecc4e.mp4

Flickering has to be fixed. Also it does not do anything useful with the found command, so it's useless right now.

**Comment by 0xAF** [comment]
Hi Daniel,
Sorry for the delay.
I was busy with other projects, but eventually got to the hobby again.
Thanks for the great work, you've done so far.
I just tested the dev branch and everything so far seems to be working as charm.
The PgUp/PgDn and the Ctrl-R searches are working nice and good.

Perhaps a small `history` function will be of use for someone, if the buffer gets larger.
I will send you a push request this night I think.

I wanted to say, that I'm not lost. I've been on other stuff, but I'm keeping an eye on your project and will try to contribute as soon as I can.

**Comment by dani007200964** [comment]
Hi Stanislav,

> I wanted to say, that I'm not lost. I've been on other stuff, but I'm keeping an eye on your project and will try to contribute as soon as I can.

Of course there are priorities, you have helped me pretty much. Thank you for that! :blush::beers:

> I was busy with other projects, but eventually got to the hobby again.

Me too, I hope your projects are going well.

> Perhaps a small history `function` will be of use for someone, if the buffer gets larger.
I will send you a push request this night I think.

I think it has to be implemented in Commander-API as you said. I'm working on some premade functions for Commander-API. The history function will be one of them.

**Comment by 0xAF** [comment]
> > Perhaps a small history `function` will be of use for someone, if the buffer gets larger.
> > I will send you a push request this night I think.
> 
> I think it has to be implemented in Commander-API as you said. I'm working on some premade functions for Commander-API. The history function will be one of them.

Yeah, I was thinking the same.
Perhaps a method to expose the current history from Shellminator would be nice. Then Commander-API or any custom command could use this array to show the history.
And one more thing.
I saw the use of `?` char in the end of the command. It's nice, but It would be nice to have some note of that in the `help` command.
And one more thing, which I find to be some sort of usual in most mini shells.
The `?` as command alone, which is an alias to `help` command.
Most people would just type `?` and expect to get some help.
:)
I'll be back on the hobby track soon.
My other projects are doing well, so I hope soon I will have more time and be able to help you a bit.

**Comment by dani007200964** [comment]
Just a small update with the WebSocket version.

https://user-images.githubusercontent.com/26076131/192574049-ef3f5d09-716a-4523-af13-4aa2632067d5.mp4

I have to work a lot on this, but seems usable already.
